# Generated by Django 5.2 on 2025-05-27 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], help_text='Kullanıcının verdiği oy (Like/Dislike).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Oyun oluşturulma zamanı.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oyun son güncellenme zamanı.')),
                ('game', models.ForeignKey(help_text='Oylanan oyun.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game')),
                ('user', models.ForeignKey(help_text='Oyu veren kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
