# Generated by Django 5.2 on 2025-05-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BUG', 'Hata / Çalışmıyor'), ('INAPPROPRIATE', 'Uygunsuz İçerik'), ('COPYRIGHT', 'Telif Hakkı İhlali'), ('SPAM', 'Spam veya Yanıltıcı'), ('OTHER', 'Diğer')], default='OTHER', help_text='Raporun nedeni.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Rapor hakkında ek detaylar (isteğe bağlı).')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('REVIEWED', 'İncelendi'), ('RESOLVED', 'Çözüldü'), ('DISMISSED', 'Reddedildi')], default='PENDING', help_text='Raporun mevcut durumu (admin tarafından yönetilir).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Raporun oluşturulma zamanı.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Raporun son güncellenme zamanı.')),
                ('game', models.ForeignKey(help_text='Raporlanan oyun.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='games.game')),
                ('reporter', models.ForeignKey(blank=True, help_text='Raporu gönderen kullanıcı (giriş yapmışsa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Raporu çözen veya inceleyen admin/yetkili kullanıcı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
