# Generated by Django 5.2 on 2025-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('BUG', 'Hata / Çalışmıyor'), ('INAPPROPRIATE', 'Uygunsuz İçerik'), ('COPYRIGHT', 'Telif Hakkı İhlali'), ('SPAM', 'Spam veya Yanıltıcı'), ('OTHER', 'Diğer')], help_text='Raporun nedeni.', max_length=20),
        ),
    ]
