# Generated by Django 5.2 on 2025-05-30 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_moderation_status_alter_game_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_published"], name="games_game_is_publ_b35f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_at"], name="games_game_created_1f2afd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="games_game_is_publ_b5db72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["creator"], name="games_game_creator_192561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["creator", "is_published"], name="games_game_creator_7de2ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["play_count"], name="games_game_play_co_be93d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["likes_count"], name="games_game_likes_c_fa3414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["view_count"], name="games_game_view_co_da6d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["moderation_status"], name="games_game_moderat_8df605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="games_game_is_publ_1f3569_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_published", "-play_count"],
                name="games_game_is_publ_60aa8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_published", "-likes_count"],
                name="games_game_is_publ_c5cd78_idx",
            ),
        ),
    ]
